server:
  port: 8181
spring:
  datasource:
    url: jdbc:h2:mem:books;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      platform: h2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/oauth-realm
          jwk-set-uri: http://localhost:8080/realms/oauth-realm/protocol/openid-connect/certs
management:
  endpoints:
    web:
      exposure:
        include: "*"
